### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by lashnag** [lavoiesl/smtp-email-validator#2]
Hello! I need to set connection timeout in SMTP. How i could do that?

**Comment by lavoiesl** [comment]
It’s currently in a property at https://github.com/lavoiesl/smtp-email-validator/blob/039b4f3ec13eb76fe4d66b9b3af288a48f46fbb1/src/Lavoiesl/Validation/Email/SMTP/Validator.php#L32, but there is no way to configure it without changing the code.

I don't really maintain this repo anymore, but you can submit a PR if you want.
